branch-defaults:
  main:
    environment: image-filter-dev
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udacity-c2-restapi
  branch: null
  default_ec2_keyname: null ###-###-###
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null ###-devops
  repository: null
  sc: git
  workspace_type: Application
